apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: primer-app-pr-tunnel-binding
subjects:
  - kind: Service
    name: primer-service
    spec:
      fqdn: pr-foo.hackworth.codes
tunnelRef:
  kind: ClusterTunnel
  name: primer-app-pr-tunnel
