apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: primer-app-pr-tunnelbinding
subjects:
  - kind: Service
    name: primer-service
    spec:
      # Note: the "x" in "pr-x" will be replaced by Kustomize with the
      # actual PR number.
      fqdn: pr-x.hackworth.dev
tunnelRef:
  kind: ClusterTunnel
  name: hackworth-dev-tunnel
  # For now, we use wildcard DNS for *.hackworth.dev, because per-fqdn
  # CNAME creation doesn't quite work right.
  disableDNSUpdates: true
