apiVersion: v1
kind: Service
metadata:
  name: primer-service
  labels:
    app.kubernetes.io/name: primer-service
spec:
  ports:
    - name: http
      port: 8081
  clusterIP: None
  selector:
    app.kubernetes.io/name: primer-service
