# Note:
#
# This StatefulSet does not make any persistent volume claims, as it's
# intended to be used only for testing. Therefore, the SQLite database
# it creates will be created in ephemeral node storage. You should not
# use this manifest for a production service!
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: primer-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: primer-service
  serviceName: "primer-service"
  replicas: 1
  minReadySeconds: 20
  template:
    metadata:
      labels:
        app.kubernetes.io/name: primer-service
    spec:
      terminationGracePeriodSeconds: 20
      containers:
        - name: primer-service
          # Note: use the *dev* version of the package here, so that
          # PRs can deploy `primer-service` container images that have
          # not yet been merged to `primer` `main`.
          image: ghcr.io/hackworthltd/primer-service-dev:git-e692f818faee0e4005c24ea1f87c1464000a91ca
          ports:
            - containerPort: 8081
          env:
            - name: SQLITE_DB
              value: primer.sqlite3
