/**
 * Generated by orval v6.12.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { InputAction } from './inputAction';
import type { ActionOneOfThreeTag } from './actionOneOfThreeTag';

export type ActionOneOfThree = {
  contents: InputAction;
  tag: ActionOneOfThreeTag;
};
