/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { NoInputAction } from './noInputAction';
import type { ActionOneOfTag } from './actionOneOfTag';

export type ActionOneOf = {
  contents: NoInputAction;
  tag: ActionOneOfTag;
};
