/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export type ActionOneOfThreeTag =
  typeof ActionOneOfThreeTag[keyof typeof ActionOneOfThreeTag];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActionOneOfThreeTag = {
  Input: "Input",
} as const;
