/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { ActionOneOf } from "./actionOneOf";
import type { ActionOneOfThree } from "./actionOneOfThree";

export type Action = ActionOneOf | ActionOneOfThree;
