/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { ActionNameOneOf } from "./actionNameOneOf";
import type { ActionNameOneOfThree } from "./actionNameOneOfThree";

export type ActionName = ActionNameOneOf | ActionNameOneOfThree;
