/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { Option } from "./option";
import type { Selection } from "./selection";

export interface ApplyActionBody {
  option: Option;
  selection: Selection;
}
