/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { InputAction } from './inputAction';

export type ApplyActionWithInputParams = {
action: InputAction;
};
