/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { ApplyActionAction } from "./applyActionAction";

export type ApplyActionParams = {
  patternsUnder?: boolean;
  action: ApplyActionAction;
};
