/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export type CreateDefinitionParams = {
name?: string;
};
