/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export type EdgeFlavor = typeof EdgeFlavor[keyof typeof EdgeFlavor];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EdgeFlavor = {
  Hole: 'Hole',
  AnnTerm: 'AnnTerm',
  Ann: 'Ann',
  AppFun: 'AppFun',
  AppArg: 'AppArg',
  ConField: 'ConField',
  Lam: 'Lam',
  LetEqual: 'LetEqual',
  LetIn: 'LetIn',
  MatchInput: 'MatchInput',
  Pattern: 'Pattern',
  MatchOutput: 'MatchOutput',
  FunIn: 'FunIn',
  FunOut: 'FunOut',
  ForallKind: 'ForallKind',
  Forall: 'Forall',
  Bind: 'Bind',
} as const;
