/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export type EvalBoundedInterpRespOneOfTag = typeof EvalBoundedInterpRespOneOfTag[keyof typeof EvalBoundedInterpRespOneOfTag];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EvalBoundedInterpRespOneOfTag = {
  EvalBoundedInterpRespTimeout: 'EvalBoundedInterpRespTimeout',
} as const;
