/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { Tree } from './tree';
import type { EvalFullRespOneOfTag } from './evalFullRespOneOfTag';

export type EvalFullRespOneOf = {
  contents: Tree;
  tag: EvalFullRespOneOfTag;
};
