/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { EvalFullRespOneOf } from './evalFullRespOneOf';
import type { EvalFullRespOneOfThree } from './evalFullRespOneOfThree';

export type EvalFullResp = EvalFullRespOneOf | EvalFullRespOneOfThree;
