/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { GlobalName } from './globalName';
import type { EvalBoundedInterpRespOneOfSevenTag } from './evalBoundedInterpRespOneOfSevenTag';

export type EvalBoundedInterpRespOneOfSeven = {
  contents: GlobalName;
  tag: EvalBoundedInterpRespOneOfSevenTag;
};
