/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export type EvalFullRespOneOfTag =
  (typeof EvalFullRespOneOfTag)[keyof typeof EvalFullRespOneOfTag];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EvalFullRespOneOfTag = {
  EvalFullRespTimedOut: "EvalFullRespTimedOut",
} as const;
