/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { GlobalName } from './globalName';
import type { EvalBoundedInterpRespOneOfFiveTag } from './evalBoundedInterpRespOneOfFiveTag';

export type EvalBoundedInterpRespOneOfFive = {
  contents: GlobalName;
  tag: EvalBoundedInterpRespOneOfFiveTag;
};
