/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export type EvalFullRespOneOfThreeTag =
  typeof EvalFullRespOneOfThreeTag[keyof typeof EvalFullRespOneOfThreeTag];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EvalFullRespOneOfThreeTag = {
  EvalFullRespNormal: "EvalFullRespNormal",
} as const;
