/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { EvalBoundedInterpRespOneOf } from './evalBoundedInterpRespOneOf';
import type { EvalBoundedInterpRespOneOfThree } from './evalBoundedInterpRespOneOfThree';
import type { EvalBoundedInterpRespOneOfFive } from './evalBoundedInterpRespOneOfFive';
import type { EvalBoundedInterpRespOneOfSeven } from './evalBoundedInterpRespOneOfSeven';
import type { EvalBoundedInterpRespOneOfNine } from './evalBoundedInterpRespOneOfNine';

export type EvalBoundedInterpResp = EvalBoundedInterpRespOneOf | EvalBoundedInterpRespOneOfThree | EvalBoundedInterpRespOneOfFive | EvalBoundedInterpRespOneOfSeven | EvalBoundedInterpRespOneOfNine;
