/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export type GetActionOptionsLevel =
  typeof GetActionOptionsLevel[keyof typeof GetActionOptionsLevel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetActionOptionsLevel = {
  Beginner: "Beginner",
  Intermediate: "Intermediate",
  Expert: "Expert",
} as const;
