/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { GetActionOptionsLevel } from "./getActionOptionsLevel";
import type { GetActionOptionsAction } from "./getActionOptionsAction";

export type GetActionOptionsParams = {
  level: GetActionOptionsLevel;
  action: GetActionOptionsAction;
};
