/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export type NodeFlavorTextBody = typeof NodeFlavorTextBody[keyof typeof NodeFlavorTextBody];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NodeFlavorTextBody = {
  Con: 'Con',
  PatternCon: 'PatternCon',
  TCon: 'TCon',
  TVar: 'TVar',
  GlobalVar: 'GlobalVar',
  LocalVar: 'LocalVar',
  VarBind: 'VarBind',
  TVarBind: 'TVarBind',
} as const;
