/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { Name } from './name';
import type { NodeBodyOneOfTag } from './nodeBodyOneOfTag';

export type NodeBodyOneOf = {
  contents: Name;
  tag: NodeBodyOneOfTag;
};
