/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { NodeFlavorNoBody } from './nodeFlavorNoBody';
import type { NodeBodyOneOfSevenTag } from './nodeBodyOneOfSevenTag';

export type NodeBodyOneOfSeven = {
  contents: NodeFlavorNoBody;
  tag: NodeBodyOneOfSevenTag;
};
