/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export type NodeBodyOneOfSevenTag = typeof NodeBodyOneOfSevenTag[keyof typeof NodeBodyOneOfSevenTag];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NodeBodyOneOfSevenTag = {
  NoBody: 'NoBody',
} as const;
