/**
 * Generated by orval v6.12.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { Tree } from './tree';
import type { NodeBodyOneOfFiveTag } from './nodeBodyOneOfFiveTag';

export type NodeBodyOneOfFive = {
  contents: Tree;
  tag: NodeBodyOneOfFiveTag;
};
