/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { NodeBodyOneOf } from './nodeBodyOneOf';
import type { NodeBodyOneOfThree } from './nodeBodyOneOfThree';
import type { NodeBodyOneOfFive } from './nodeBodyOneOfFive';

export type NodeBody = NodeBodyOneOf | NodeBodyOneOfThree | NodeBodyOneOfFive;
