/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { Tree } from './tree';
import type { NodeBodyOneOfThreeTag } from './nodeBodyOneOfThreeTag';

export type NodeBodyOneOfThree = {
  contents: Tree;
  tag: NodeBodyOneOfThreeTag;
};
