/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { NodeBodyOneOfSevenTag } from './nodeBodyOneOfSevenTag';

export type NodeBodyOneOfSeven = {
  tag: NodeBodyOneOfSevenTag;
};
