/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export type NodeFlavorTextBody = typeof NodeFlavorTextBody[keyof typeof NodeFlavorTextBody];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NodeFlavorTextBody = {
  Con: 'Con',
  Lam: 'Lam',
  LAM: 'LAM',
  Let: 'Let',
  LetType: 'LetType',
  Letrec: 'Letrec',
  PatternBind: 'PatternBind',
  PatternCon: 'PatternCon',
  TCon: 'TCon',
  TVar: 'TVar',
  TForall: 'TForall',
  TLet: 'TLet',
  GlobalVar: 'GlobalVar',
  LocalVar: 'LocalVar',
} as const;
