/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export type NodeFlavorNoBody = typeof NodeFlavorNoBody[keyof typeof NodeFlavorNoBody];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NodeFlavorNoBody = {
  Hole: 'Hole',
  EmptyHole: 'EmptyHole',
  Ann: 'Ann',
  App: 'App',
  APP: 'APP',
  Case: 'Case',
  CaseWith: 'CaseWith',
  TEmptyHole: 'TEmptyHole',
  THole: 'THole',
  TFun: 'TFun',
  TApp: 'TApp',
} as const;
