/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { NodeType } from './nodeType';

export interface NodeSelection {
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  meta: number;
  nodeType: NodeType;
}
