/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export type NodeBodyOneOfThreeTag = typeof NodeBodyOneOfThreeTag[keyof typeof NodeBodyOneOfThreeTag];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NodeBodyOneOfThreeTag = {
  PrimBody: 'PrimBody',
} as const;
