/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export type NodeBodyOneOfFiveTag = typeof NodeBodyOneOfFiveTag[keyof typeof NodeBodyOneOfFiveTag];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NodeBodyOneOfFiveTag = {
  BoxBody: 'BoxBody',
} as const;
