/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { RecordPairNodeFlavorPrimBodyPrimCon } from './recordPairNodeFlavorPrimBodyPrimCon';
import type { NodeBodyOneOfThreeTag } from './nodeBodyOneOfThreeTag';

export type NodeBodyOneOfThree = {
  contents: RecordPairNodeFlavorPrimBodyPrimCon;
  tag: NodeBodyOneOfThreeTag;
};
