/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export type NodeBodyOneOfTag = typeof NodeBodyOneOfTag[keyof typeof NodeBodyOneOfTag];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NodeBodyOneOfTag = {
  TextBody: 'TextBody',
} as const;
