/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export type NoInputAction = typeof NoInputAction[keyof typeof NoInputAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NoInputAction = {
  MakeCase: 'MakeCase',
  MakeApp: 'MakeApp',
  MakeAPP: 'MakeAPP',
  MakeAnn: 'MakeAnn',
  RemoveAnn: 'RemoveAnn',
  LetToRec: 'LetToRec',
  Raise: 'Raise',
  EnterHole: 'EnterHole',
  RemoveHole: 'RemoveHole',
  DeleteExpr: 'DeleteExpr',
  MakeFun: 'MakeFun',
  AddInput: 'AddInput',
  MakeTApp: 'MakeTApp',
  RaiseType: 'RaiseType',
  DeleteType: 'DeleteType',
  DuplicateDef: 'DuplicateDef',
  DeleteDef: 'DeleteDef',
  DeleteTypeDef: 'DeleteTypeDef',
  DeleteCon: 'DeleteCon',
  AddConField: 'AddConField',
  DeleteConField: 'DeleteConField',
  DeleteTypeParam: 'DeleteTypeParam',
  MakeKType: 'MakeKType',
  MakeKFun: 'MakeKFun',
  DeleteKind: 'DeleteKind',
} as const;
