/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { Tree } from './tree';
import type { OkOrMismatchOneOfTag } from './okOrMismatchOneOfTag';

export type OkOrMismatchOneOf = {
  contents: Tree;
  tag: OkOrMismatchOneOfTag;
};
