/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export type OkOrMismatchOneOfTag = typeof OkOrMismatchOneOfTag[keyof typeof OkOrMismatchOneOfTag];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OkOrMismatchOneOfTag = {
  Ok: 'Ok',
} as const;
