/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { Option } from "./option";

export interface Options {
  free: boolean;
  opts: Option[];
}
