/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export interface Option {
  /** @minItems 1 */
  context?: string[];
  matchesType: boolean;
  option: string;
}
