/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export interface PaginatedMeta {
  firstPage: number;
  lastPage: number;
  nextPage?: number;
  pageSize: number;
  prevPage?: number;
  thisPage: number;
  totalItems: number;
}
