/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { Session } from './session';
import type { PaginatedMeta } from './paginatedMeta';

export interface PaginatedSession {
  items: Session[];
  meta: PaginatedMeta;
}
