/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { PrimConOneOf } from './primConOneOf';
import type { PrimConOneOfThree } from './primConOneOfThree';

export type PrimCon = PrimConOneOf | PrimConOneOfThree;
