/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export type PrimConOneOfFiveTag = typeof PrimConOneOfFiveTag[keyof typeof PrimConOneOfFiveTag];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PrimConOneOfFiveTag = {
  PrimAnimation: 'PrimAnimation',
} as const;
