/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export type PrimConOneOfThreeTag = typeof PrimConOneOfThreeTag[keyof typeof PrimConOneOfThreeTag];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PrimConOneOfThreeTag = {
  PrimInt: 'PrimInt',
} as const;
