/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { Module } from './module';
import type { Selection } from './selection';

export interface Prog {
  modules: Module[];
  redoAvailable: boolean;
  selection?: Selection;
  undoAvailable: boolean;
}
