/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { EdgeFlavor } from './edgeFlavor';
import type { Tree } from './tree';

export interface RecordPairEdgeFlavorTree {
  fst: EdgeFlavor;
  snd: Tree;
}
