/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { NodeFlavorPrimBody } from './nodeFlavorPrimBody';
import type { PrimCon } from './primCon';

export interface RecordPairNodeFlavorPrimBodyPrimCon {
  fst: NodeFlavorPrimBody;
  snd: PrimCon;
}
