/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { DefSelection } from './defSelection';
import type { SelectionOneOfTag } from './selectionOneOfTag';

export type SelectionOneOf = {
  contents: DefSelection;
  tag: SelectionOneOfTag;
};
