/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { TypeDefSelection } from './typeDefSelection';
import type { SelectionOneOfThreeTag } from './selectionOneOfThreeTag';

export type SelectionOneOfThree = {
  contents: TypeDefSelection;
  tag: SelectionOneOfThreeTag;
};
