/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { GlobalName } from "./globalName";
import type { NodeSelection } from "./nodeSelection";

export interface Selection {
  def: GlobalName;
  node?: NodeSelection;
}
