/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { SelectionOneOf } from './selectionOneOf';
import type { SelectionOneOfThree } from './selectionOneOfThree';

export type Selection = SelectionOneOf | SelectionOneOfThree;
