/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { Tree } from './tree';
import type { TypeOrKindOneOfTag } from './typeOrKindOneOfTag';

export type TypeOrKindOneOf = {
  contents: Tree;
  tag: TypeOrKindOneOfTag;
};
