/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export type TypeDefNodeSelectionOneOfThreeTag = typeof TypeDefNodeSelectionOneOfThreeTag[keyof typeof TypeDefNodeSelectionOneOfThreeTag];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TypeDefNodeSelectionOneOfThreeTag = {
  TypeDefConsNodeSelection: 'TypeDefConsNodeSelection',
} as const;
