/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { TypeDefNodeSelectionOneOf } from './typeDefNodeSelectionOneOf';
import type { TypeDefNodeSelectionOneOfThree } from './typeDefNodeSelectionOneOfThree';

export type TypeDefNodeSelection = TypeDefNodeSelectionOneOf | TypeDefNodeSelectionOneOfThree;
