/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { TypeOrKindOneOf } from './typeOrKindOneOf';
import type { TypeOrKindOneOfThree } from './typeOrKindOneOfThree';

export type TypeOrKind = TypeOrKindOneOf | TypeOrKindOneOfThree;
