/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { TypeDefConsSelection } from './typeDefConsSelection';
import type { TypeDefNodeSelectionOneOfThreeTag } from './typeDefNodeSelectionOneOfThreeTag';

export type TypeDefNodeSelectionOneOfThree = {
  contents: TypeDefConsSelection;
  tag: TypeDefNodeSelectionOneOfThreeTag;
};
