/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { GlobalName } from './globalName';
import type { TypeDefConsFieldSelection } from './typeDefConsFieldSelection';

export interface TypeDefConsSelection {
  con: GlobalName;
  field?: TypeDefConsFieldSelection;
}
