/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export type TypeDefNodeSelectionOneOfTag = typeof TypeDefNodeSelectionOneOfTag[keyof typeof TypeDefNodeSelectionOneOfTag];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TypeDefNodeSelectionOneOfTag = {
  TypeDefParamNodeSelection: 'TypeDefParamNodeSelection',
} as const;
