/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { ValCon } from './valCon';
import type { GlobalName } from './globalName';

export interface TypeDef {
  constructors?: ValCon[];
  name: GlobalName;
  nameHints: string[];
  params: string[];
}
