/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { OkOrMismatch } from './okOrMismatch';
import type { TypeOrKindOneOfThreeTag } from './typeOrKindOneOfThreeTag';

export type TypeOrKindOneOfThree = {
  contents: OkOrMismatch;
  tag: TypeOrKindOneOfThreeTag;
};
