/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { TypeDefNodeSelectionOneOfTag } from './typeDefNodeSelectionOneOfTag';

export type TypeDefNodeSelectionOneOf = {
  contents: string;
  tag: TypeDefNodeSelectionOneOfTag;
};
