/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export type TypeOrKindOneOfTag = typeof TypeOrKindOneOfTag[keyof typeof TypeOrKindOneOfTag];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TypeOrKindOneOfTag = {
  Type: 'Type',
} as const;
