/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export type TypeOrKindOneOfThreeTag = typeof TypeOrKindOneOfThreeTag[keyof typeof TypeOrKindOneOfThreeTag];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TypeOrKindOneOfThreeTag = {
  Kind: 'Kind',
} as const;
