app = "hackworth-code"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  SQLITE_DB = "/data/primer.sqlite3"

[mounts]
source="sqlite"
destination="/data"

[metrics]
  # Note: this is the same as the service port because the metrics are
  # also served by WAI.
  port = 8081
  path = "/metrics"
  
[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8081
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
