env:
  CACHIX_CONFIG: /var/lib/cachix/hackworthltd-private/cachix.dhall
  CACHIX_CACHE: hackworthltd-private

agents:
  private: "true"
  os: "linux"

steps:
  - command: nix-buildkite
    label: ":nixos: :buildkite:"
    plugins:
      - circuithub/nix-buildkite:
          file: ci.nix
          post-build-hook:
            /run/current-system/sw/bin/buildkite-private-post-build-hook
  - label: ":nixos: Archive Nix flake inputs"
    command: nix flake archive --json | jq -r '.path,(.inputs|to_entries[].value.path)' | cachix --verbose --config "$CACHIX_CONFIG" push "$CACHIX_CACHE"
  - wait
  - label: ":nixos: :linux: Cache the Nix shell"
    command: |
      nix develop --print-build-logs --profile /tmp/primer-app --command cachix --verbose --config "$CACHIX_CONFIG" push "$CACHIX_CACHE" /tmp/primer-app
  - label: ":nixos: :macos: Cache the Nix shell"
    command: |
      nix develop --print-build-logs --profile /tmp/primer-app --command cachix --verbose --config "$CACHIX_CONFIG" push "$CACHIX_CACHE" /tmp/primer-app
    agents:
      os: "darwin"

  # Currently disabled due to:
  # https://github.com/hackworthltd/primer-app/pull/339

  # - label: ":chromatic: Trigger Chromatic deployment"
  #   trigger: primer-app-chromatic
  #   # This can't be async, because we need to be sure the Chromatic
  #   # deployment succeeded before merging via Bors.
  #   async: false
  #   build:
  #     message: "${BUILDKITE_MESSAGE}"
  #     commit: "${BUILDKITE_COMMIT}"
  #     branch: "${BUILDKITE_BRANCH}"
  #     env:
  #       BUILDKITE_PULL_REQUEST: "${BUILDKITE_PULL_REQUEST}"
  #       BUILDKITE_PULL_REQUEST_BASE_BRANCH: "${BUILDKITE_PULL_REQUEST_BASE_BRANCH}"
  #       BUILDKITE_PULL_REQUEST_REPO: "${BUILDKITE_PULL_REQUEST_REPO}"
