agents:
  private: "true"

steps:
  - command: nix-buildkite
    label: ":nixos: :buildkite:"
    plugins:
      - hackworthltd/nix-buildkite#hackworthltd-v5:
          file: ci.nix
          post-build-hook:
            /run/current-system/sw/bin/buildkite-private-post-build-hook
  - wait
  - label: ":chromatic: Trigger Chromatic deployment"
    trigger: primer-app-chromatic
    # This can't be async, because we need to be sure the Chromatic
    # deployment succeeded before merging via Bors.
    async: false
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        BUILDKITE_PULL_REQUEST: "${BUILDKITE_PULL_REQUEST}"
        BUILDKITE_PULL_REQUEST_BASE_BRANCH: "${BUILDKITE_PULL_REQUEST_BASE_BRANCH}"
        BUILDKITE_PULL_REQUEST_REPO: "${BUILDKITE_PULL_REQUEST_REPO}"
