name: Bug report
description: Report a bug or defect
labels: ["triage"]
assignees:
  - dhess

body:
  - type: markdown
    id: preamble
    attributes:
      value: |
        Thanks for helping us improve Primer App!

        This bug reporting form includes a number of fields. Some are required, and some are optional, but the more detail you can provide, the easier it'll be for us to determine the source of the issue, and potentially fix it.

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of conduct
      description: To participate in this project, you must agree to abide by the project's [code of conduct](https://github.com/hackworthltd/primer-app/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I've read the project's code of conduct, and agree to follow it.
          required: true

  - type: checkboxes
    id: not-a-security-issue
    attributes:
      label: Don't report security issues here
      description: If this bug is a security issue, please do not report the bug using GitHub Issues.
      options:
        - label: I've read the project's [security policy](https://github.com/hackworthltd/primer-app/security/policy), and I do not believe this bug is a security issue.
          required: true

  - type: checkboxes
    id: new-issue
    attributes:
      label: Is there an existing issue?
      description: Please search the project's GitHub Issues for an existing, similar issue.
      options:
        - label: I've searched GitHub Issues, and I believe this is a new issue
          required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Please provide a clear and concise description of the defective behavior.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: What should have happened?
      description: Please provide a clear and concise description of the behavior you expected.
    validations:
      required: true

  - type: dropdown
    id: problem-source
    attributes:
      label: Which component(s) or aspect(s) of the project are the source of the issue?
      description: If your issue is caused by the included `primer-service` server, or related to some aspect of the Primer programming language, please open an issue on the [`primer` project](https://github.com/hackworthltd/primer/blob/main/CONTRIBUTING.md#-opening-a-github-issue), instead.
      options:
        - one or more React components
        - the project's Storybook
        - the web application itself
        - the Primer API
        - build system and/or tooling
        - documentation
        - other
        - not sure
      multiple: true
    validations:
      required: true

  - type: textarea
    id: bugreport-output
    attributes:
      label: Developers, please provide the output of the bug report script
      description: If you're a developer, please [run the project's bug report script](https://github.com/hackworthltd/primer-app/blob/main/CONTRIBUTING.md#-reporting-bugs) and include the output here.
      render: true

  - type: dropdown
    id: browser
    attributes:
      label: Which browser(s) exhibit the issue, if applicable?
      options:
        - Safari
        - Chrome
        - Firefox
        - Edge
        - other (please specify in additional information below)
      multiple: true

  - type: dropdown
    id: platform
    attributes:
      label: On which platform(s) does your browser exhibit the issue, if applicable?
      options:
        - macOS
        - iOS
        - Android
        - Linux
        - Windows
        - other (please specify in additional information below)
      multiple: true

  - type: textarea
    id: reproducer
    attributes:
      label: Do you have a reproducer?
      description: If you have an example project, test case, or simple program that demonstrates the issue, please link to it or paste it here.

  - type: textarea
    id: additional-info
    attributes:
      label: Any additional information?
      description: Please add any additional relevant information about the problem here, such as your browser & browser platform versions, user agent, etc.
