/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export type ActionType = typeof ActionType[keyof typeof ActionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActionType = {
  Primary: "Primary",
  Destructive: "Destructive",
} as const;
