/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { Pair } from "./pair";
import type { Tree } from "./tree";

export interface Box {
  ann: string;
  childTrees: Pair[];
  colour: string;
  inside: Tree;
}
