/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export type ChildDir = typeof ChildDir[keyof typeof ChildDir];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChildDir = {
  ChildLeft: "ChildLeft",
  ChildRight: "ChildRight",
  ChildBottom: "ChildBottom",
} as const;
