/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { Tree } from "./tree";

export interface Def {
  name: string;
  term?: Tree;
  type_: Tree;
}
