/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { EitherBoxTreeOneOf } from "./eitherBoxTreeOneOf";
import type { EitherBoxTreeOneOfTwo } from "./eitherBoxTreeOneOfTwo";

export type EitherBoxTree = EitherBoxTreeOneOf | EitherBoxTreeOneOfTwo;
