/**
 * Generated by orval v6.6.4 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export type GetSessionListParams = {
  inMemory?: boolean;
  page?: number;
  pageSize?: number;
};
