/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export interface ModuleName {
  unModuleName: string[];
}
