/**
 * Generated by orval v6.9.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export type NodeStyle = typeof NodeStyle[keyof typeof NodeStyle];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NodeStyle = {
  StyleHole: "StyleHole",
  StyleEmptyHole: "StyleEmptyHole",
  StyleAnn: "StyleAnn",
  StyleApp: "StyleApp",
  StyleAPP: "StyleAPP",
  StyleCon: "StyleCon",
  StyleLam: "StyleLam",
  StyleLAM: "StyleLAM",
  StyleVar: "StyleVar",
  StyleGlobalVarRef: "StyleGlobalVarRef",
  StyleLocalVarRef: "StyleLocalVarRef",
  StyleLet: "StyleLet",
  StyleLetType: "StyleLetType",
  StyleLetrec: "StyleLetrec",
  StyleCase: "StyleCase",
  StylePrimCon: "StylePrimCon",
  StyleTEmptyHole: "StyleTEmptyHole",
  StyleTHole: "StyleTHole",
  StyleTCon: "StyleTCon",
  StyleTFun: "StyleTFun",
  StyleTVar: "StyleTVar",
  StyleTApp: "StyleTApp",
  StyleTForall: "StyleTForall",
  StylePattern: "StylePattern",
} as const;
