/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export type NodeType = typeof NodeType[keyof typeof NodeType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NodeType = {
  BodyNode: "BodyNode",
  SigNode: "SigNode",
} as const;
