/**
 * Generated by orval v6.9.2 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export type NodeFlavor = typeof NodeFlavor[keyof typeof NodeFlavor];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NodeFlavor = {
  FlavorHole: "FlavorHole",
  FlavorEmptyHole: "FlavorEmptyHole",
  FlavorAnn: "FlavorAnn",
  FlavorApp: "FlavorApp",
  FlavorAPP: "FlavorAPP",
  FlavorCon: "FlavorCon",
  FlavorLam: "FlavorLam",
  FlavorLAM: "FlavorLAM",
  FlavorGlobalVar: "FlavorGlobalVar",
  FlavorLocalVar: "FlavorLocalVar",
  FlavorLet: "FlavorLet",
  FlavorLetType: "FlavorLetType",
  FlavorLetrec: "FlavorLetrec",
  FlavorCase: "FlavorCase",
  FlavorPrimCon: "FlavorPrimCon",
  FlavorTEmptyHole: "FlavorTEmptyHole",
  FlavorTHole: "FlavorTHole",
  FlavorTCon: "FlavorTCon",
  FlavorTFun: "FlavorTFun",
  FlavorTVar: "FlavorTVar",
  FlavorTApp: "FlavorTApp",
  FlavorTForall: "FlavorTForall",
  FlavorPattern: "FlavorPattern",
  FlavorPatternCon: "FlavorPatternCon",
  FlavorPatternBind: "FlavorPatternBind",
  FlavorPatternApp: "FlavorPatternApp",
} as const;
