/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { NodeBodyOneOfFiveTag } from "./nodeBodyOneOfFiveTag";

export type NodeBodyOneOfFive = {
  tag: NodeBodyOneOfFiveTag;
};
