/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { EitherBoxTree } from "./eitherBoxTree";
import type { ChildDir } from "./childDir";

export interface Pair {
  fstPair: EitherBoxTree;
  sndPair: ChildDir;
}
