/**
 * Generated by orval v6.9.2 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { Uuid } from "./uuid";
import type { SessionName } from "./sessionName";

export interface Session {
  id: Uuid;
  name: SessionName;
}
