/**
 * Generated by orval v6.5.1 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export interface Tree {
  childTrees: Tree[];
  nodeId: number;
  label: string;
}
