/**
 * Generated by orval v6.9.0 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { NodeBody } from "./nodeBody";
import type { NodeStyle } from "./nodeStyle";

export interface Tree {
  body: NodeBody;
  childTrees: Tree[];
  label: string;
  nodeId: string;
  rightChild?: Tree;
  style: NodeStyle;
}
