/**
 * Generated by orval v6.10.1 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */
import type { ActionNameOneOfThreeTag } from "./actionNameOneOfThreeTag";

export type ActionNameOneOfThree = {
  contents: string;
  tag: ActionNameOneOfThreeTag;
};
