/**
 * Generated by orval v6.7.1 🍺
 * Do not edit manually.
 * Primer backend API
 * A backend service implementing a pedagogic functional programming language.
 * OpenAPI spec version: 0.7
 */

export type InitialApp = "NewApp" | "NewEmptyApp";

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InitialApp = {
  NewApp: "NewApp" as InitialApp,
  NewEmptyApp: "NewEmptyApp" as InitialApp,
};
