name: Build the frontend

on:
  push:

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 7.1.7

      - name: Setup nodejs
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 14
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the frontend
        run: pnpm build

      # Note: linting must come after building, or else eslint won't
      # be able to resolve some paths.
      - name: Lint
        run: pnpm lint
