name: Build the frontend

on:
  workflow_call:
    inputs:
      api-url:
        required: true
        type: string
      withCredentials:
        required: true
        type: boolean

jobs:
  build-frontend:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 8.6.2

      - name: Setup nodejs
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18.x
          check-latest: true
          # Disabled until we can satisfy Tidy.
          #node-version-file: package.json
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Audit is disabled for now. See discussion at:
      # https://github.com/hackworthltd/primer-app/pull/1005

      # Note: we only audit non-dev dependencies, because there are
      # nearly always dev dependency vulnerabilities, but they're very
      # unlikely to affect the production app.
      # - name: Audit
      #   run: pnpm audit --prod

      - name: Build the frontend
        # This URL scheme for PR's is baked into other parts of the
        # repo, so if you change it here, make sure you change it
        # elsewhere, as well (and vice versa).
        run: VITE_API_URL="${{ inputs.api-url }}" VITE_WITH_CREDENTIALS="${{ inputs.withCredentials }}" pnpm build

      # Note: linting must come after building, or else eslint won't
      # be able to resolve some paths.
      - name: Lint
        run: pnpm lint --max-warnings=0

      - name: Archive frontend
        uses: actions/upload-artifact@v4.3.3
        with:
          name: dist
          path: |
            dist

