name: Update Nix dependencies.

on:
  workflow_dispatch:
  schedule:
    # 2am every Sunday
    - cron: '0 2 * * 0'

jobs:
  update-nix-dependencies:
    uses: hackworthltd/.github/.github/workflows/reusable-update-nix-flake-public.yml@main
