name: Deploy the frontend (production)

on:
  workflow_dispatch:
  # This project is deprecated.
  #push:
    # branches:
    #   - main

jobs:
  build-frontend-production:
    permissions:
      contents: read
    uses: ./.github/workflows/build-frontend.yaml
    with:
      api-url: "https://api.hackworth.codes/"
      withCredentials: true

  deploy-frontend-production:
    needs: build-frontend-production
    permissions:
      contents: read
      id-token: write
      deployments: write
    uses: ./.github/workflows/deploy-frontend.yaml
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
