name: Deploy Storybook.js

on:
  push:
    branches-ignore:
      # Do not run this workflow on Dependabot updates, or else it'll
      # absolutely kill our GitHub Action & Chromatic CI minutes.
      - dependabot/**

jobs:
  deploy-to-chromatic:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          # Required by the Chromatic GitHub Action
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 7.1.0

      - name: Setup nodejs
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 14
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Import secrets from Vault
        uses: hashicorp/vault-action@v2.4.1
        id: secrets
        with:
          url: https://secrets.hackworth-corp.com
          path: "github-actions"
          caCertificate: ${{ secrets.VAULT_CA_CERT }}
          role: primer-app-workflow-chromatic
          method: jwt
          secrets: |
            secret/data/chromatic/primer-app token | CHROMATIC_PROJECT_TOKEN ;

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: packages/primer-components
          projectToken: ${{ env.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
          exitZeroOnChanges: true
