name: Deploy the frontend (PR)

on:
  workflow_dispatch:

  # This project is deprecated.
  #pull_request:
  #merge_group:

jobs:
  build-frontend-pr:
    permissions:
      contents: read
    uses: ./.github/workflows/build-frontend.yaml
    with:
      api-url: "https://pr-${{ github.event.pull_request.number }}.hackworth.dev/"
      withCredentials: false

  deploy-frontend-pr:
    needs: build-frontend-pr
    permissions:
      contents: read
      id-token: write
      deployments: write
    uses: ./.github/workflows/deploy-frontend.yaml
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
