name: Deploy Storybook.js

on:
  push:
    branches-ignore:
      # Do not run this workflow on Dependabot updates, or else it'll
      # absolutely kill our GitHub Action & Chromatic CI minutes.
      - dependabot/**

jobs:
  deploy-to-chromatic:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          # Required by the Chromatic GitHub Action
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.6.2

      - name: Setup nodejs
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18.x
          check-latest: true
          # Disabled until we can satisfy Tidy.
          #node-version-file: package.json
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Storybook
        run: pnpm build-storybook

      - name: Import secrets from Vault
        uses: hashicorp/vault-action@v2.7.3
        id: secrets
        with:
          url: https://vault.hackworth-corp.com
          path: "github-actions"
          role: primer-app-workflow-chromatic
          method: jwt
          secrets: |
            secret/data/chromatic/primer-app token | CHROMATIC_PROJECT_TOKEN ;

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          storybookBuildDir: storybook-static
          projectToken: ${{ env.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
          exitZeroOnChanges: true
