name: Deploy to Fly.io

on:
  push:
    # branches:
    #   - main

jobs:
  deploy-to-flyio:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Import secrets from Vault
        uses: hashicorp/vault-action@v2.4.1
        id: secrets
        with:
          url: https://secrets.hackworth-corp.com
          path: "github-actions"
          caCertificate: ${{ secrets.VAULT_CA_CERT }}
          role: primer-app-workflow-flyio
          method: jwt
          jwtTtl: 3600
          secrets: |
            secret/data/cachix/hackworthltd-private/github-workflows token | CACHIX_AUTH_TOKEN ;
            secret/data/flyio/github token | FLY_API_TOKEN ;
            /github/token/primer-app-repos token | NIX_GITHUB_TOKEN ;

      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            substituters = https://cache.nixos.org?priority=10 https://hackworthltd.cachix.org?priority=30 https://hydra.iohk.io?priority=50 https://cache.zw3rk.com?priority=60
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hackworthltd.cachix.org-1:0JTCI0qDo2J+tonOalrSQP3yRNleN6bQucJ05yDltRI= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= loony-tools:pr9m4BkM/5/eSTZlkQyRt57Jz7OMBxNSUiMC4FkcNfk=
            access-tokens = github.com=${{ env.NIX_GITHUB_TOKEN }}

      - name: Configure hackworthltd-private Cachix cache
        uses: cachix/cachix-action@v10
        with:
          name: hackworthltd-private
          skipPush: true
          authToken: '${{ env.CACHIX_AUTH_TOKEN }}'

      - name: Checkout repo
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

        # Note: this step shouldn't actually build the Docker image.
        # It should come from our Cachix cache, as by the time there's
        # a push to the main branch, this exact Nix derivation should
        # have been built by CI during the merge queue step.
      - name: Load the primer-service Docker image.
        shell: bash
        run: |
          nix-build -A packages.x86_64-linux.primer-service-docker-image
          IMAGE=$(docker load --quiet < result | grep -Po 'Loaded image: \Kprimer-service:.*')
          echo "Loaded image: ${IMAGE}"
          NAME=primer-service:${{ github.sha }}
          docker tag "$IMAGE" "$NAME"
          echo "local_docker_image_tag=$NAME" >> "$GITHUB_ENV"

      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.0.353

      - name: Deploy the primer-service Docker image to Fly.io.
        run: |
          flyctl deploy --image ${{ env.local_docker_image_tag }} --image-label ${{ github.sha }}
