name: Deploy primer-service

# Ensure only one production deployment happens at a time.
#
# We *do* allow concurrent production deployments to all production
# apps, however.

concurrency:
  group: production-hackworth-codes

on:
  workflow_run:
    workflows:
      - Build the frontend
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    name: Deploy primer-service
    runs-on: ubuntu-latest

    # Only run if the triggering workflow was successful.
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: read
      id-token: write
      deployments: write

    environment:
      name: "Production (service)"
      url: https://fly.io/apps/hackworth-code

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.0.2
        with:
          # Required by flakes
          fetch-depth: 0

      - name: Import secrets from Vault
        uses: hashicorp/vault-action@v2.5.0
        id: secrets
        with:
          url: https://secrets.hackworth-corp.com
          path: "github-actions"
          caCertificate: ${{ secrets.VAULT_CA_CERT }}
          role: primer-app-workflow-flyio
          method: jwt
          secrets: |
            secret/data/flyio/github token | FLY_API_TOKEN ;
            secret/data/flyio/github database_url | DATABASE_URL ;
            /github/token/primer-app-repos token | NIX_GITHUB_TOKEN ;
            secret/data/cachix/hackworthltd-private/github-workflows token | CACHIX_AUTH_TOKEN ;

      - name: Install & configure Nix for primer and primer-app Hackworth Ltd repos
        uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hackworthltd.cachix.org-1:0JTCI0qDo2J+tonOalrSQP3yRNleN6bQucJ05yDltRI= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= loony-tools:pr9m4BkM/5/eSTZlkQyRt57Jz7OMBxNSUiMC4FkcNfk=
            substituters = https://cache.nixos.org?priority=10 https://hackworthltd.cachix.org?priority=30 https://cache.iog.io?priority=40 https://cache.zw3rk.com?priority=50

      - name: Configure Cachix for private Hackworth Ltd cache
        uses: cachix/cachix-action@v12
        with:
          name: hackworthltd-private
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true

      - name: Fetch primer-service-docker-image
        run: |
          nix build --access-tokens github.com=${{ secrets.NIX_GITHUB_TOKEN }} -L .#packages.x86_64-linux.primer-service-docker-image 

      - name: Load Docker image
        run: |
          IMAGE=$(docker load --quiet < result | grep -Po 'Loaded image: \Kprimer-service:.*')
          LABEL=$(echo "$IMAGE" | grep -Po 'primer-service:\K.*')
          echo "Loaded Docker image: $IMAGE"
          echo "docker_image=$IMAGE" >> "$GITHUB_ENV"
          echo "docker_image_label=$LABEL" >> "$GITHUB_ENV"

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Setup flyctl proxy
        run: |
          flyctl proxy 5432 -a hackworth-code-postgres &
          sleep 10

      - name: Deploy database changes
        run: |
          nix run .#primer-sqitch -- deploy --verify db:"$DATABASE_URL"

      - name: Deploy Docker image
        run: |
          flyctl deploy --image "$docker_image" --image-label "$docker_image_label"
